# Generated by Django 5.2 on 2025-06-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item_itemcategory_auctionlisting_user_watchlist_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
