# Generated by Django 5.2 on 2025-06-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_item_category_delete_itemcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.URLField(),
        ),
    ]
