# Generated by Django 5.2 on 2025-06-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_created_date_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='hightest_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_for_listing', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='bids',
            field=models.ManyToManyField(related_name='bids_for_listing', to='auctions.bid'),
        ),
    ]
