# Generated by Django 5.2 on 2025-06-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='hightest_bid',
        ),
    ]
