# Generated by Django 5.2 on 2025-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='flights.flight'),
        ),
    ]
